name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'k8s-deployment.yaml'
      - 'src/**'
      - '*.js'   # include other source files if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

      # Step 5: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 6: Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name wisecow-cluster

      # Step 7: Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest
          kubectl rollout status deployment/wisecow-deployment

